service: hello-groogle
provider:
    name: google
    stage: dev
    runtime: nodejs8
    region: us-central1
    project: MYPROJECTHERE
    credentials: ~/.gcloud/keyfile.json
plugins:
    - serverless-google-cloudfunctions
package:
    exclude:
        - 'node_modules/**'
        - .gitignore
        - '.git/**'
functions:
    first:
        handler: http
        events:
            - 
                http: path
